export enum Actions {
  ALL_AUTHORS = "ALL_AUTHORS",
  RECEIVED_AUTHORS = "RECEIVED_AUTHORS",
  INIT_AUTHORS = "INIT_AUTHORS",
  ALL_COURSES = "ALL_COURSES",
  RECEIVED_COURSES = "RECEIVED_COURSES",
  INIT_COURSES = "INIT_COURSES",
  ADD_COURSES = "ADD_COURSES",
  COURSE_BY_ID = "COURSE_BY_ID",
  RECEIVED_COURSE_BY_ID = "RECEIVED_COURSE_BY_ID",
  EDIT_COURSE = "EDIT_COURSE",
  DELETE_COURSE = "DELETE_COURSE"
}
