export enum Actions {
  ALL_AUTHORS = "ALL_AUTHORS",
  RECEIVED_AUTHORS = "RECEIVED_AUTHORS",
  INIT_AUTHORS = "INIT_AUTHORS",
  ALL_COURSES = "ALL_COURSES",
  RECEIVED_COURSES = "RECEIVED_COURSES",
  INIT_COURSES = "INIT_COURSES",
}
